# Generated by Django 3.1.8 on 2021-06-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='language',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
